import hero from '@/assets/new-hero.jpg';
import audio from '@/assets/new-audio.jpg';
import production from '@/assets/new-production.jpg';
import conference from '@/assets/hero-stage.jpg';
import broadcast from '@/assets/work-broadcast.jpg';
import exhibition from '@/assets/work-expo.jpg';
import speaker from '@/assets/work-keynote.jpg';
import panel from '@/assets/work-panel.jpg';

export const services = [
  { slug: 'audio', title: 'Audio', description: 'Concert-grade sound systems with experienced engineers, from a single podium mic to a full band.', image: audio, alt: 'Audio engineer at a live mixing desk', heading: 'Never miss a beat.', intro: 'Powerful, crystal-clear sound engineered for the room.', paragraphs: ['Excellent sound starts with the right equipment and the right engineer. For medium and large events we deploy professional line-array systems; for smaller rooms we use compact systems that are heard rather than seen. Every system is matched with audio technicians who can engineer anything from a single podium microphone to a band, a large conference, a product launch or a presentation.'], listTitle: 'A typical sound system includes', items: ['Top-end loudspeaker systems', 'A digital mixing console', 'Experienced technicians for set-up and breakdown', 'A dedicated audio engineer'], extra: 'We carry a full range of: microphones · consoles · backline · DJ equipment · stage monitors', metaTitle: 'Event Sound & PA Systems Hyderabad | The Event Tribe', metaDescription: 'Line-array sound, digital consoles and expert engineers for conferences, concerts and weddings across Hyderabad.' },
  { slug: 'video', title: 'Video', description: 'HD projection, LED walls, media servers and 3D video mapping.', image: production, alt: 'Immersive LED screens at a live production', heading: 'The magic of the moving image.', intro: '', paragraphs: ["Audiences now expect high-definition moving images everywhere, from giant public screens to the phone in their hand. Bringing that quality into your event is no longer optional. We've invested in high-powered projectors, LED video walls, media servers and video switchers to suit any event, plus LCD, LFD and LED displays in all sizes for corporate and retail uses.", 'We love pushing creative boundaries: motorised unveilings at a launch, video synchronised to a moving-light show at a party, 3D video mapping with HD projectors. We bring high-tech video from leading brands to make your event unforgettable.'], listTitle: 'Capabilities', items: ['HD projection', 'LED video walls', 'LED/LCD/LFD displays', 'Media servers & switchers', '3D video mapping', 'Stealth video walls', 'Graphic design & content'], metaTitle: 'LED Video Walls & Projection Hyderabad | The Event Tribe', metaDescription: 'HD projectors, LED walls, media servers and 3D video mapping for launches, conferences and shows.' },
  { slug: 'lighting', title: 'Lighting', description: 'From elegant ballroom washes to full concert light shows.', image: audio, alt: 'Amber lighting beams across a live stage', heading: 'Setting the right mood.', intro: '', paragraphs: ['Lighting transforms a drab space into a vibrant one. It does more than illuminate; like music, it creates the energy and pulse of an event. That is our lighting philosophy.', 'We work with modern, energy-efficient fixtures, and we build the right support structure for your venue, whether hung from the architecture or ground-supported. Systems are elegant and, above all, safe. Structures can be camouflaged into the environment or shown off as a design feature. We also offer custom gobos to carry your brand into the light. Small boutique event in an unusual space or a large conference, we supply power distribution and generation too.'], listTitle: 'Techniques we use', items: ['Corporate: LED uplighting · feature product lighting · wireless table pinspotting · custom gobos · lit podiums and catwalks', 'Entertainment: moving lights · strobes and blinders · lasers · haze and low-lying fog', 'Trade exhibitions: false-ceiling lights · tile lights'], metaTitle: 'Event Lighting Hyderabad | The Event Tribe', metaDescription: 'Ballroom to concert lighting design, custom gobos and safe rigging for corporate and entertainment events.' },
  { slug: 'staging', title: 'Staging', description: 'Custom modular stages, motorised truss, podiums and catwalks, with power.', image: conference, alt: 'Large stage with production rigging', heading: 'The backbone of a production.', intro: '', paragraphs: ['The best gear in the world is useless without something safe to hang it from. We build beautiful structures that stay unobtrusive and never compromise safety.', 'We create self-contained temporary stages and motorised truss systems that suit your lighting, sound and video needs and the building itself. Modular staging covers everything from a simple riser for a speech, concert or DJ to full fashion-show runways. Step-and-repeats, podiums and branded elements can be supplied and lit at the same time.', 'Aesthetics matter. We dress most truss in white, black or custom-coloured fabric and hide cables carefully. In spaces with no infrastructure, we build the environment from the ground up and provide the power distribution and generation to run it.'], listTitle: 'Includes', items: ['Motorised truss', 'Self-climbing roof systems', 'Modular stages', 'Catwalks & runways', 'Podiums', 'Branded step-and-repeats', 'Power distribution & generation'], metaTitle: 'Stage, Truss & Power Hyderabad | The Event Tribe', metaDescription: 'Custom modular stages, motorised truss, branded podiums and event power for any venue.' },
  { slug: 'event-production', title: 'Event Production', description: 'Light, sound, video and staging engineered as one cohesive experience.', image: production, alt: 'Integrated stage production with light and video', heading: 'One conductor. One orchestra.', intro: '', paragraphs: ['Creating the wow factor usually comes down to technology, and to how well it works together. Our greatest strength is blending lighting, staging, audio and video into a single, cohesive experience. We act as both conductor and orchestra.', 'Experienced planners, agencies and in-house teams rely on us for stress-free, spectacular events.'], listTitle: 'How we work', items: ['Listen. We review your brief and constraints and present options within your range.', 'Pre-produce. We select gear, coordinate with partners, and plan power and schedules.', 'Visualise. We provide 3D renderings, CAD files, schematics, walk-throughs and a run of show.', 'Engineer. We map every cue, plan back-ups and build redundancy.', 'Deliver. We run the show on event day, from the first cue to the last.'], extra: 'Available: automated and conventional lighting · public address · HD video walls · LED screens · graphic design · laser shows · special effects · full power', metaTitle: '360° Event Production Hyderabad | The Event Tribe', metaDescription: 'Lighting, audio, video and staging engineered as one system, with CAD, 3D renders and full pre-production.' },
  { slug: 'hybrid-events', title: 'Hybrid Events', description: 'Live streaming and broadcast for audiences near and far.', image: broadcast, alt: 'Broadcast control at a conference', heading: "Going hybrid? Here's how to broadcast your live event.", intro: '', paragraphs: ['Conferences, festivals and launches increasingly combine in-person and online audiences. Whether you have 20 attendees or 10,000, a live stream can be the right call: it keeps remote attendees in the know, extends your reach, keeps your brand present, and gives you footage for future marketing.'], listTitle: 'We handle', items: ['Camera gear and streaming distribution', 'Risers, tripods and staging', 'Stream hosting services', 'Graphics, titles and slide design', 'Video and content creation', 'Music and playlist curation between sessions', 'Creative direction'], metaTitle: 'Hybrid & Live Stream Events Hyderabad | The Event Tribe', metaDescription: 'Multi-camera live streaming, graphics and hybrid event production for 20 to 10,000 attendees.' },
] as const;

export const events = [
  { slug: 'conferences', title: 'Meetings & Conferences', description: 'Your vision, executed with meticulous attention to detail.', image: conference, alt: 'Conference stage and audience', heading: 'Meetings & conferences.', intro: 'Incredible things happen when people get together. Our role is to make your job easier.', paragraphs: ['We deliver in-person, virtual and hybrid events with confidence and a genuine commitment to reliability. Take a single service, a few, or complete meeting management. Our team has worked on everything from large corporate meetings to small non-profit symposiums, and understands how to engage audiences face to face and online.', 'Our on-site technical team stands beside speakers on stage and handles any emergency, because one glitch can sink a conference.', 'Experiential marketing firms, event management companies, planners and in-house teams rely on us for stress-free, sensational events with a meticulous eye for detail.'], extra: 'Medical & scientific congresses: multi-hall AV, speaker support, recording, hybrid delivery.', metaTitle: 'Conference AV & Production Hyderabad | The Event Tribe', metaDescription: 'Reliable AV for medical, corporate and academic conferences, in person, virtual or hybrid.' },
  { slug: 'trade-exhibitions', title: 'Trade Exhibitions', description: 'Stages and spaces where buyers meet your brand.', image: exhibition, alt: 'Exhibition production space', heading: 'Where buyer, seller and product meet.', intro: '', paragraphs: ['In a digital age, exhibitions are the one medium where all three come together in person. We create theme-specific brand experiences that start a real dialogue, going well beyond a product display, through the right format, programme and staging.', 'Individual trade-fair events, exclusive production visits, road trips, showroom events and anniversary events: we put together a predictable cost package that fits your annual planning. Our team covers project management, staging, design, production, lighting, sound, décor and technical planning, A to Z.'], metaTitle: 'Exhibition Production Hyderabad | The Event Tribe', metaDescription: 'Stands, staging, lighting and AV for trade fairs and showroom events with predictable cost packages.' },
  { slug: 'entertainment', title: 'Entertainment Events', description: 'Shows that feel sensational and unforgettable.', image: audio, alt: 'Live performance and concert lighting', heading: 'Make it sensational.', intro: '', paragraphs: ['Concert-grade sound, moving lights, strobes, lasers, haze and LED visuals, synchronised and engineered for the show. We produce music performances, album release parties, fashion shows and after-parties, movie premieres, dance parties and live concerts.'], extra: 'Capabilities: line-array sound, band & DJ equipment, monitors · moving-light and effects rigs · video synced to lighting · runways & stages · power', metaTitle: 'Concert & Entertainment Production Hyderabad | The Event Tribe', metaDescription: 'Concert sound, moving lights, lasers and LED for music events, fashion shows and premieres.' },
  { slug: 'weddings-and-social', title: 'Weddings & Social Events', description: 'Celebrations lit, heard and seen at their best.', image: panel, alt: 'Warmly lit gathering on stage', heading: 'Celebrations, beautifully produced.', intro: '', paragraphs: ['We work with every kind of client, from DIY couples to professional wedding planners. We listen, respect your budget and your venue, and present a production plan within your range.', "We're known for transforming unusual locations. We handle audio, lighting, video and atmosphere, plus power generation and distribution. Our trained technicians operate everything, and our equipment is carefully maintained, so you never face outdated or worn gear."], extra: 'A sampling of what we offer: wireless LED uplighting · vivid wall tones · audio consoles · DJ equipment · high-powered projectors · LED/LCD screens', metaTitle: 'Wedding & Social Event Production Hyderabad | The Event Tribe', metaDescription: 'Lighting, sound, DJ and LED screens for weddings and celebrations in any venue.' },
] as const;

export const photos = [
  { image: hero, alt: 'Event auditorium with technical production', category: 'Conferences' },
  { image: conference, alt: 'Medical conference stage', category: 'Conferences' },
  { image: speaker, alt: 'Speaker at a conference lectern', category: 'Conferences' },
  { image: exhibition, alt: 'Exhibition floor production', category: 'Exhibitions' },
  { image: audio, alt: 'Concert mixing desk and stage', category: 'Entertainment' },
  { image: production, alt: 'Integrated lighting and video stage', category: 'Staging' },
  { image: panel, alt: 'Panel event on stage', category: 'Weddings' },
  { image: broadcast, alt: 'Live broadcast production', category: 'Lighting' },
];
